# Generated by Django 3.1.7 on 2021-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
